# Generated by Django 5.1.1 on 2024-09-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('design', 'Design'), ('writing', 'Writing'), ('programming', 'Programming'), ('marketing', 'Marketing'), ('management', 'Management'), ('nft', 'NFT Creation'), ('content', 'Content Creation'), ('teamwork', 'Teamwork'), ('adaptability', 'Adaptability'), ('attention_to_detail', 'Attention to Detail'), ('collaboration', 'Collaboration')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('project_manager', 'Project Manager')], default='creator', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(related_name='skills', to='accounts_api.skill'),
        ),
    ]
